
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("USAGE", "Nix07:Using directive is unnecessary", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.ModelDescriptions.ModelDescriptionGenerator.GetOrCreateModelDescription(System.Type)~WebApiTokenUser.Areas.HelpPage.ModelDescriptions.ModelDescription")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("USAGE", "Nix08:Variable isn't used", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageConfigurationExtensions.InitializeModelDescriptionGenerator(System.Web.Http.HttpConfiguration)~WebApiTokenUser.Areas.HelpPage.ModelDescriptions.ModelDescriptionGenerator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix01:Line is too long", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.ModelDescriptions.ModelDescriptionGenerator.GenerateComplexTypeModelDescription(System.Type)~WebApiTokenUser.Areas.HelpPage.ModelDescriptions.ModelDescription")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.ObjectGenerator.GenerateObject(System.Type,System.Collections.Generic.Dictionary{System.Type,System.Object})~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageConfig.Register(System.Web.Http.HttpConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageConfigurationExtensions.GenerateUriParameters(WebApiTokenUser.Areas.HelpPage.Models.HelpPageApiModel,WebApiTokenUser.Areas.HelpPage.ModelDescriptions.ModelDescriptionGenerator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.ObjectGenerator.GenerateGenericType(System.Type,System.Int32,System.Collections.Generic.Dictionary{System.Type,System.Object})~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("LAYOUT", "Nix06:The end of the file must be a curly bracket", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("USAGE", "Nix08:Variable isn't used", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator.ResolveHttpRequestMessageType(System.Web.Http.Description.ApiDescription)~System.Type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("USAGE", "Nix09:The parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator.GetActionSample(System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.Type,System.Net.Http.Formatting.MediaTypeFormatter,System.Net.Http.Headers.MediaTypeHeaderValue,WebApiTokenUser.Areas.HelpPage.SampleDirection)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix04:Too many parameters in method", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator.ResolveType(System.Web.Http.Description.ApiDescription,System.String,System.String,System.Collections.Generic.IEnumerable{System.String},WebApiTokenUser.Areas.HelpPage.SampleDirection,System.Collections.ObjectModel.Collection{System.Net.Http.Formatting.MediaTypeFormatter}@)~System.Type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix04:Too many parameters in method", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator.GetActionSample(System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.Type,System.Net.Http.Formatting.MediaTypeFormatter,System.Net.Http.Headers.MediaTypeHeaderValue,WebApiTokenUser.Areas.HelpPage.SampleDirection)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("USAGE", "Nix09:The parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator.DefaultSampleObjectFactory(WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator,System.Type)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("DESIGN", "Nix02:Method is too long", Justification = "<Pending>", Scope = "member", Target = "~M:WebApiTokenUser.Areas.HelpPage.HelpPageSampleGenerator.WriteSampleObjectUsingFormatter(System.Net.Http.Formatting.MediaTypeFormatter,System.Object,System.Type,System.Net.Http.Headers.MediaTypeHeaderValue)~System.Object")]

